### ISSUE TITLE
Screenshot?

### ISSUE THREAD

**Issue by benknoble** [jeetsukumaran/vim-markology#11]
I *personally* would like to see a screenshot make it's way into the README, just so that I can see what the plugin looks like before trying it out.

Thoughts?

**Comment by jeetsukumaran** [comment]
Sound good. Happy to accept a PR!

**Comment by benknoble** [comment]
> Happy to accept a PR!

Would send one, but not currently using Markology :P perhaps I'll try it out and send one.
